### PR TITLE
Add CS2C as a gogs user

### PR DESCRIPTION
**Pull request by imjoey**
I'm working at CS2C and we are using gogs as internal Git platform. So if possible, I'd like to let everyone know we're using gogs. Thank team for this great work.

Signed-off-by: imjoey <majunjiev@gmail.com>

### CODE REVIEW

**Comment by unknwon** [comment]
Thank you!

**Comment by unknwon** [comment]
HTML and assets will have to be updated via a `git pull` on the server, but I'm on my laptop and don't have access to the server right now. I will update within next 48 hours.

**Comment by imjoey** [comment]
> HTML and assets will have to be updated via a `git pull` on the server, but I'm on my laptop and don't have access to the server right now. I will update within next 48 hours.

Thank you so much for reviewing.

**Comment by imjoey** [comment]
> HTML and assets will have to be updated via a `git pull` on the server, but I'm on my laptop and don't have access to the server right now. I will update within next 48 hours.

Thank you so much for reviewing.

**Comment by unknwon** [comment]
It is now live on https://gogs.io/.

**Comment by imjoey** [comment]
> It is now live on https://gogs.io/.

Many thanks. And, may I ask why the new logo is not shown properly and the area seems not big enough. Much appreciated.

**Comment by imjoey** [comment]
FYI, if I replace the link of logo image to `https://github.com/gogs/gogsweb.peach/blob/master/public/img/brands/cs2c.png?raw=true` , the image would be shown in a good shape. If I miss something, please let me know. Thank you very much.

**Comment by unknwon** [comment]
I purged CDN cache, it looks fine after a hard refresh (<kbd>cmd+r</kbd>).

**Comment by imjoey** [comment]
> I purged CDN cache, it looks fine after a hard refresh (cmd+r).

Yep, it shows as expected after several refreshes. Thank you so much for the efforts and we love gogs ❤️

**Pull request merged**
